//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Billing
{
    public partial class Plans
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblCurrentPlan;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Label lblBasicStatus;
        protected global::System.Web.UI.WebControls.Panel pnlPremiumActive;
        protected global::System.Web.UI.WebControls.Panel pnlPremiumUpgrade;
        protected global::System.Web.UI.WebControls.Button btnUpgrade;
        protected global::System.Web.UI.WebControls.Button btnConfirmUpgrade;
        protected global::System.Web.UI.WebControls.Panel pnlNoPayments;
        protected global::System.Web.UI.WebControls.Repeater rptPayments;
    }
}
