//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Learner
{
    public partial class Chapter
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.PlaceHolder phLearnerNavigation;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminNavigation;
        protected global::System.Web.UI.WebControls.PlaceHolder phLearnerActions;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminActions;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlAdminPreview;
        protected global::System.Web.UI.WebControls.Panel pnlChapter;
        protected global::System.Web.UI.WebControls.PlaceHolder phLearnerBreadcrumb;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminBreadcrumb;
        protected global::System.Web.UI.WebControls.HyperLink lnkBreadcrumbCourse;
        protected global::System.Web.UI.WebControls.HyperLink lnkBreadcrumbModule;
        protected global::System.Web.UI.WebControls.Label lblChapterID;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.HyperLink lnkCourse;
        protected global::System.Web.UI.WebControls.HyperLink lnkAssistant;
        protected global::System.Web.UI.WebControls.Panel pnlTutorial;
        protected global::System.Web.UI.WebControls.Label lblTutorialTitle;
        protected global::System.Web.UI.WebControls.Literal litMaterials;
        protected global::System.Web.UI.WebControls.Panel pnlNoTutorial;
        protected global::System.Web.UI.WebControls.Panel pnlExercise;
        protected global::System.Web.UI.WebControls.Label lblExerciseQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtAnswer;
        protected global::System.Web.UI.WebControls.Button btnCheckAnswer;
        protected global::System.Web.UI.WebControls.Label lblExerciseResult;
        protected global::System.Web.UI.WebControls.Panel pnlQuizLink;
        protected global::System.Web.UI.WebControls.HyperLink lnkQuiz;
        protected global::System.Web.UI.WebControls.Label lblChapterNavigationNote;
        protected global::System.Web.UI.WebControls.HyperLink lnkNextChapter;
    }
}
