//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Learner
{
    public partial class Course
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlCourse;
        protected global::System.Web.UI.WebControls.Label lblCourseID;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblDifficulty;
        protected global::System.Web.UI.WebControls.Panel pnlNotEnrolled;
        protected global::System.Web.UI.WebControls.HyperLink lnkEnroll;
        protected global::System.Web.UI.WebControls.Panel pnlContent;
        protected global::System.Web.UI.WebControls.Panel pnlNoContent;
        protected global::System.Web.UI.WebControls.Repeater rptModules;
    }
}
