//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Learner
{
    public partial class Enroll
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlCourse;
        protected global::System.Web.UI.WebControls.Label lblCourseID;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblDifficulty;
        protected global::System.Web.UI.WebControls.Label lblPlan;
        protected global::System.Web.UI.WebControls.Panel pnlPlanAllowed;
        protected global::System.Web.UI.WebControls.Button btnEnroll;
        protected global::System.Web.UI.WebControls.Panel pnlLocked;
        protected global::System.Web.UI.WebControls.Label lblLocked;
        protected global::System.Web.UI.WebControls.Panel pnlAlreadyEnrolled;
    }
}
