//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Learner
{
    public partial class Quiz
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Label lblBreadcrumbCourse;
        protected global::System.Web.UI.WebControls.Label lblBreadcrumbChapter;
        protected global::System.Web.UI.WebControls.Label lblChapterID;
        protected global::System.Web.UI.WebControls.Label lblChapterTitle;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackToChapter;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlQuestions;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.Button btnSubmitQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Label lblResult;
        protected global::System.Web.UI.WebControls.Label lblSaveNotice;
    }
}
