//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.AI
{
    public partial class Assistant
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlLocked;
        protected global::System.Web.UI.WebControls.Panel pnlAssistant;
        protected global::System.Web.UI.WebControls.Label lblContextTitle;
        protected global::System.Web.UI.WebControls.Label lblCourse;
        protected global::System.Web.UI.WebControls.Label lblModule;
        protected global::System.Web.UI.WebControls.Label lblChapter;
        protected global::System.Web.UI.WebControls.Repeater rptMessages;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.TextBox txtPrompt;
        protected global::System.Web.UI.WebControls.Button btnAsk;
    }
}
