//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Support
{
    public partial class Tickets
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlNoTickets;
        protected global::System.Web.UI.WebControls.Repeater rptTickets;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtSubject;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Button btnCreateTicket;
        protected global::System.Web.UI.WebControls.Panel pnlSelectedTicket;
        protected global::System.Web.UI.WebControls.Label lblTicketID;
        protected global::System.Web.UI.WebControls.Label lblTicketSubject;
        protected global::System.Web.UI.WebControls.Label lblTicketStatus;
        protected global::System.Web.UI.WebControls.Label lblTicketCategory;
        protected global::System.Web.UI.WebControls.Label lblTicketName;
        protected global::System.Web.UI.WebControls.Label lblTicketDescription;
        protected global::System.Web.UI.WebControls.Repeater rptReplies;
        protected global::System.Web.UI.WebControls.Panel pnlReply;
        protected global::System.Web.UI.WebControls.TextBox txtReply;
        protected global::System.Web.UI.WebControls.Button btnReply;
        protected global::System.Web.UI.WebControls.Panel pnlClosedNotice;
    }
}
