//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Admin
{
    public partial class Content
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourses;
        protected global::System.Web.UI.WebControls.Label lblSelectedCourse;
        protected global::System.Web.UI.WebControls.HyperLink lnkPreviewCourse;
        protected global::System.Web.UI.WebControls.TextBox txtCourseTitle;
        protected global::System.Web.UI.WebControls.TextBox txtCourseDescription;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourseDifficulty;
        protected global::System.Web.UI.WebControls.Button btnCreateCourse;
        protected global::System.Web.UI.WebControls.Panel pnlNoCourse;
        protected global::System.Web.UI.WebControls.Panel pnlModuleEditor;
        protected global::System.Web.UI.WebControls.DropDownList ddlModules;
        protected global::System.Web.UI.WebControls.Label lblSelectedModule;
        protected global::System.Web.UI.WebControls.TextBox txtModuleTitle;
        protected global::System.Web.UI.WebControls.TextBox txtModuleDescription;
        protected global::System.Web.UI.WebControls.DropDownList ddlModuleStatus;
        protected global::System.Web.UI.WebControls.Button btnCreateModule;
        protected global::System.Web.UI.WebControls.Repeater rptModules;
        protected global::System.Web.UI.WebControls.Panel pnlNoModule;
        protected global::System.Web.UI.WebControls.Panel pnlChapterEditor;
        protected global::System.Web.UI.WebControls.TextBox txtChapterTitle;
        protected global::System.Web.UI.WebControls.TextBox txtChapterDescription;
        protected global::System.Web.UI.WebControls.Button btnCreateChapter;
        protected global::System.Web.UI.WebControls.Repeater rptChapters;
    }
}
