//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Admin
{
    public partial class Lessons
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.DropDownList ddlTutorials;
        protected global::System.Web.UI.WebControls.Label lblSelectedTutorial;
        protected global::System.Web.UI.WebControls.HyperLink lnkPreviewTutorial;
        protected global::System.Web.UI.WebControls.LinkButton btnPublishTutorial;
        protected global::System.Web.UI.WebControls.LinkButton btnReviewTutorial;
        protected global::System.Web.UI.WebControls.TextBox txtTutorialTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlTutorialCategory;
        protected global::System.Web.UI.WebControls.TextBox txtTutorialMaterials;
        protected global::System.Web.UI.WebControls.DropDownList ddlTutorialStatus;
        protected global::System.Web.UI.WebControls.Button btnCreateTutorial;
        protected global::System.Web.UI.WebControls.Panel pnlNoTutorial;
        protected global::System.Web.UI.WebControls.Panel pnlExerciseEditor;
        protected global::System.Web.UI.WebControls.Repeater rptExercises;
        protected global::System.Web.UI.WebControls.TextBox txtExerciseQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtExerciseAnswer;
        protected global::System.Web.UI.WebControls.Button btnCreateExercise;
        protected global::System.Web.UI.WebControls.DropDownList ddlChapters;
        protected global::System.Web.UI.WebControls.Label lblSelectedChapter;
        protected global::System.Web.UI.WebControls.HyperLink lnkPreviewChapter;
        protected global::System.Web.UI.WebControls.HyperLink lnkPreviewQuiz;
        protected global::System.Web.UI.WebControls.TextBox txtQuizDescription;
        protected global::System.Web.UI.WebControls.TextBox txtQuizQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtQuizCorrectAnswer;
        protected global::System.Web.UI.WebControls.TextBox txtQuizAnswers;
        protected global::System.Web.UI.WebControls.Button btnCreateQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlNoChapter;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
    }
}
