//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Admin
{
    public partial class Users
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClearSearch;
        protected global::System.Web.UI.WebControls.Label lblDirectoryTitle;
        protected global::System.Web.UI.WebControls.Label lblUserCount;
        protected global::System.Web.UI.WebControls.Panel pnlNoUsers;
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.Panel pnlSelectUser;
        protected global::System.Web.UI.WebControls.Panel pnlSelectedUser;
        protected global::System.Web.UI.WebControls.Label lblSelectedUserID;
        protected global::System.Web.UI.WebControls.Label lblSelectedUsername;
        protected global::System.Web.UI.WebControls.Label lblSelectedRole;
        protected global::System.Web.UI.WebControls.Label lblSelectedEmail;
        protected global::System.Web.UI.WebControls.Label lblSelectedGoogle;
        protected global::System.Web.UI.WebControls.Label lblSelectedEnrollments;
        protected global::System.Web.UI.WebControls.Label lblSelectedTickets;
        protected global::System.Web.UI.WebControls.Label lblSelectedBio;
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;
        protected global::System.Web.UI.WebControls.DropDownList ddlPlan;
        protected global::System.Web.UI.WebControls.Button btnSaveAccess;
    }
}
