//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest.Features.Public
{
    public partial class Tutorial
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.PlaceHolder phPublicNavigation;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminNavigation;
        protected global::System.Web.UI.WebControls.PlaceHolder phPublicActions;
        protected global::System.Web.UI.WebControls.PlaceHolder phLearnerActions;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminActions;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlAdminPreview;
        protected global::System.Web.UI.WebControls.Panel pnlTutorial;
        protected global::System.Web.UI.WebControls.Label lblTutorialID;
        protected global::System.Web.UI.WebControls.Label lblCategory;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Panel pnlHtmlGuide;
        protected global::System.Web.UI.WebControls.Panel pnlMaterials;
        protected global::System.Web.UI.WebControls.Literal litMaterials;
        protected global::System.Web.UI.WebControls.Panel pnlNoMaterials;
        protected global::System.Web.UI.WebControls.Panel pnlExercise;
        protected global::System.Web.UI.WebControls.Label lblExerciseQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtAnswer;
        protected global::System.Web.UI.WebControls.Button btnCheckAnswer;
        protected global::System.Web.UI.WebControls.Label lblExerciseResult;
    }
}
