//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest
{
    public partial class AdminDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblCourses;
        protected global::System.Web.UI.WebControls.Label lblModules;
        protected global::System.Web.UI.WebControls.Label lblChapters;
        protected global::System.Web.UI.WebControls.Label lblTutorials;
        protected global::System.Web.UI.WebControls.Label lblExercises;
        protected global::System.Web.UI.WebControls.Label lblQuizzes;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
