//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeQuest
{
    public partial class ForgotPassword
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnRequestReset;
        protected global::System.Web.UI.WebControls.Panel pnlLocalReset;
        protected global::System.Web.UI.WebControls.HyperLink lnkLocalReset;
        protected global::System.Web.UI.WebControls.Label lblExpiry;
    }
}
